return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "vimdoc",
      "html",
      "css",
      "scss",
      "json",
      "lua",
      -- "markdown",
      -- "markdown_inline",
      "python",
      "query",
      "regex",
      "vim",
      "yaml",
      "go",
      "bicep",
      "terraform",
      "c_sharp",
      "javascript",
      "typescript",
      "sql",
      "http",
    },
  },
}
