import = [
    "~/.config/alacritty/themes/themes/github_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 24

[font.normal]
family = "Mononoki Nerd Font"

[window]
decorations = "none"
opacity = 0.9
blur = true

[window.padding]
x = 10
y = 5

[colors.primary]
background = '#242424'
